gowin: add missing stdexcept required by runtime_error
fix:
src/gowin.cpp:73:11: error: 'runtime_error' is not a member of 'std'
      throw std::runtime_error("both write-flash and write-sram can't be set");
            ^
src/gowin.cpp:81:10: error: 'runtime_error' is not a member of 'std'
      throw std::runtime_error("incompatible file format");
            ^